name: PR Approved

on:
   push:
    branches: [ master ]

jobs:
  build:
    runs-on: latest
    steps:
      - uses: actions/checkout@
      - uses: ruby/setup-ruby@
      - run: ruby .github/convert.rb
      - name: Push changes
        uses: actions-go/push@
        with:
          force: false
          author-name: AwesomeSwift Bot
          commit-message: 'Updated markdown'